### ISSUE TITLE
length of OTP code

### ISSUE THREAD

**Issue by dhrjyaduvanshi** [Himanshu44ec06/IshineProject#1]
Sometime OTP generated, have a length less than  what it should be i.e . I get OTP of length of 1 ,2,3 ...

**Comment by Himanshu44ec06** [comment]
Would please provide a  use case when u r facing this issue, that would be very help full 
Thanks

**Comment by dhrjyaduvanshi** [comment]
i simple call generateOTP Api,and some time OTP returned,of length <4(i set locally length of otp 4
![screenshot 2018-11-20 at 2 00 03 pm](https://user-images.githubusercontent.com/36765737/48760759-e38dba80-eccc-11e8-861c-1750e1ec3bfe.png)
)

**Comment by Himanshu44ec06** [comment]
Would  you please check now .. take update

**Comment by dhrjyaduvanshi** [comment]
This error still persist with new code

**Comment by Himanshu44ec06** [comment]
Fixed

**Comment by Himanshu44ec06** [comment]
Resolved
